// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcojctzbcjbmpbcnqles.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjb2pjdHpiY2pibXBiY25xbGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDA4MzAsImV4cCI6MjA1NjY3NjgzMH0.iXyQEDDGJsfNDilnWIYbfKAvcAetjsS4Tqtf6xbaSHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);